version: '3.8'

services:
  backend:
    build: ./backend
    container_name: heic-backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - heic-network

  frontend:
    build: ./frontend
    container_name: heic-frontend
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - heic-network

networks:
  heic-network:
    driver: bridge
